// GENERATED by tools/fetch_player_photos.py: the real persons that have a photo in assets/players/<person>.webp.
// Photos are freely licensed (CC0 / Public domain / CC BY / CC BY-SA) from Wikimedia Commons; see assets/players/credits.json
// and credits.html. Do not edit by hand.
export const PLAYER_PHOTOS = new Set([
  "alisson", "benzema", "cavani", "courtois", "debruyne", "diogocosta",
  "donnarumma", "ederson", "emimartinez", "kobel", "lukaku", "maignan",
  "mamardashvili", "mbappe", "messi", "modric", "neuer", "neymar",
  "oblak", "onana", "ramos", "raya", "ronaldo", "rubendias",
  "salah", "sommer", "terstegen", "unaisimon", "vandijk", "vicario",
]);
