import assert from 'node:assert/strict';
import { createOnline } from '../services.js';
import { createMockBackend, memoryStore } from '../mockbackend.js';

const mem = () => { const m = new Map(); return { getItem: (k) => m.get(k) || null, setItem: (k, v) => m.set(k, String(v)), removeItem: (k) => m.delete(k) }; };
let clock = Date.UTC(2026, 8, 29);
const backend = createMockBackend(memoryStore(), { now: () => clock });
const account = () => createOnline({ rpc: (fn, args) => backend.call(fn, args), storage: mem(), volatileStorage: mem(), transportKind: 'loopback', requireAccount: true });
const owner = account(), player = account(), other = account();
const pass = 'Blue-Kite-42';

const o = await owner.account.signup({ username: 'Shawky Fc', password: pass, confirm: pass, adminCode: 'mock-super' });
const p = await player.account.signup({ username: 'Vinson Tester', password: pass, confirm: pass });
const q = await other.account.signup({ username: 'Other Tester', password: pass, confirm: pass });
assert.equal(o.ok, true); assert.equal(p.ok, true); assert.equal(q.ok, true);
assert.equal((await owner.vinson.pull()).exempt, true);
assert.equal((await player.vinson.pull()).phase, 'doom');
const first = await player.vinson.status();
assert.equal(first.phase, 'doom');
assert.equal((await player.vinson.pull()).deadline, first.deadline, 'cannot restart the countdown');
assert.equal((await other.vinson.unban(p.id)).error, 'not_allowed');
clock += 180001;
assert.equal((await player.account.status()).state, 'banned', 'reload/login detects an expired deadline');
assert.equal((await player.vinson.status()).phase, 'banned', 'raw status works while banned');
assert.equal((await player.profile()).error, 'banned');
assert.equal((await owner.moderation.unban(p.id)).ok, true, 'owner panel releases the Vinson ban');
assert.equal((await player.vinson.status()).phase, 'released');
assert.equal((await player.account.status()).state, 'account');
assert.equal((await player.vinson.lock()).phase, 'locked');
assert.equal((await player.vinson.status()).phase, 'locked');
assert.equal((await player.cloud.put({ club: [], squad: { slots: [], bench: [] } }, 0)).error, 'vinson_locked', 'cloud save cannot strip a locked card');
assert.equal((await other.moderation.unban(p.id)).error, 'not_admin');
console.log('1 Vinson server/account test passed');
