#!/usr/bin/env python3
"""Writes 3d/js/meta/core/cardink.js: per card design, the text colour that reads on the two places text sits.

  top  = rating / position / badge column (top-left of the card)
  band = name + six stats (lower band)

The card is drawn stretched to 10 x 14 em, so the regions are fractions of the image, not pixels.
The design's own ink (carddesigns.js, tinted gold/brown/cream) is kept when it already has the right polarity for
the region; otherwise plain near-black / near-white is used. Re-run after tools/fetch_card_designs.py.
"""
import json, os, re
from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '3d')
SRC = os.path.join(ROOT, 'js/meta/core/carddesigns.js')
OUT = os.path.join(ROOT, 'js/meta/core/cardink.js')
DARK_INK, LIGHT_INK = '#17130a', '#f7f3e8'
REGIONS = {'top': (.06, .07, .36, .50), 'band': (.16, .55, .84, .90)}


def lum(rgb):
    return .2126 * rgb[0] + .7152 * rgb[1] + .0722 * rgb[2]


def hex_lum(h):
    h = h.lstrip('#')
    return lum(tuple(int(h[i:i + 2], 16) for i in (0, 2, 4)))


def region_lum(im, box):
    w, h = im.size
    crop = im.crop((int(w * box[0]), int(h * box[1]), int(w * box[2]), int(h * box[3]))).resize((32, 32))
    px = [p for p in crop.getdata() if p[3] > 200]
    if not px:
        return 128
    ls = sorted(lum(p) for p in px)
    return ls[len(ls) // 2]  # median: a few bright/dark art details must not decide


def pick(bg_lum, design_ink):
    want_dark = bg_lum >= 135
    if (hex_lum(design_ink) < 135) == want_dark:
        return design_ink
    return DARK_INK if want_dark else LIGHT_INK


def main():
    text = open(SRC, encoding='utf-8').read()
    designs = json.loads(text[text.index('= {') + 2:text.rindex('};') + 1])
    out = {}
    for key, d in sorted(designs.items()):
        path = os.path.join(ROOT, d['file'])
        if not os.path.exists(path):
            continue
        im = Image.open(path).convert('RGBA')
        out[key] = [pick(region_lum(im, REGIONS['top']), d['ink']), pick(region_lum(im, REGIONS['band']), d['ink'])]
    lines = ['// GENERATED by tools/card_ink.py: per card design [ink for the rating column, ink for the name + stats band].',
             '// Falls back to CARD_DESIGNS[key].ink when a key is missing.',
             'export const CARD_INK = {']
    lines += [f'  {json.dumps(k)}: {json.dumps(v)},' for k, v in out.items()]
    lines.append('};')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print(len(out), 'designs ->', os.path.relpath(OUT))


main()
