#!/usr/bin/env python3
"""EA SPORTS card designs (blank card backgrounds) for the card faces (owner, Sep 30: use the real FIFA / FC designs;
non-commercial fan game). Sources, all via FUT.GG's asset CDN:
  * FIFA 22 / FIFA 23 / FC 24: every rarity background  2023/rarities/<eaRarityId>_e_<level>.png            -> key f22|f23|fc24-<id>[-<level>]
  * FC 25 / FC 26 / FC 27: the rarity backgrounds named in the fut.gg player pages cached by photos_futgg.py
    (<year>/rarities-level-<level>-large/<eaRarityId>.<hash>.png)                              -> key fc26-<id>-<level>
Writes 3d/assets/cards/<key>.webp (420 px wide, alpha) and 3d/js/meta/core/carddesigns.js:
  CARD_DESIGNS = { key: { file, ink, dark } }  ink = text colour picked from the lower half of the card.

  python3 tools/fetch_card_designs.py [--cache tools/.futgg_cache]
"""
import argparse, io, json, os, re, sys, time, urllib.request
sys.path.insert(0, os.path.dirname(__file__))
import fetch_player_photos as F  # noqa: E402  (proxy-aware opener, ROOT)

OUT = os.path.join(F.ROOT, '3d', 'assets', 'cards')
JS = os.path.join(F.ROOT, '3d', 'js', 'meta', 'core', 'carddesigns.js')
CDN = 'https://game-assets.fut.gg/cdn-cgi/image/quality=90,format=png,width=420/'
UA = 'Mozilla/5.0 PitchsideFanGame/1.0 (non-commercial school fan game)'
_last = [0.0]


def get(url):
    for attempt in range(4):
        wait = 0.5 - (time.time() - _last[0])
        if wait > 0:
            time.sleep(wait)
        _last[0] = time.time()
        try:
            with F._opener.open(urllib.request.Request(url, headers={'User-Agent': UA}), timeout=60) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            if e.code in (404, 403):
                return None
            time.sleep(5 * (attempt + 1))
        except Exception:  # noqa: BLE001
            time.sleep(5 * (attempt + 1))
    return None


def ink_for(im):
    """(text colour, dark background?) from the lower half, where the name and stats sit."""
    from PIL import Image
    px = [p for p in im.crop((int(im.width * .15), int(im.height * .55), int(im.width * .85), int(im.height * .9)))
          .resize((40, 40)).getdata() if p[3] > 200]
    if not px:
        return '#1b1b1b', False
    lum = sum(.2126 * r + .7152 * g + .0722 * b for r, g, b, _ in px) / len(px)
    return ('#f4efe2', True) if lum < 140 else ('#20190c', False)


def save(key, data, designs):
    from PIL import Image
    im = Image.open(io.BytesIO(data)).convert('RGBA')
    bb = im.getbbox()
    if bb:
        im = im.crop(bb)
    im = im.resize((420, round(420 * im.height / im.width)), Image.LANCZOS)
    buf = io.BytesIO(); im.save(buf, 'WEBP', quality=86, method=6)
    open(os.path.join(OUT, key + '.webp'), 'wb').write(buf.getvalue())
    ink, dark = ink_for(im)
    designs[key] = {'file': f'assets/cards/{key}.webp', 'ink': ink, 'dark': dark}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cache', default=os.path.join(F.ROOT, 'tools', '.futgg_cache'))
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    designs = {}
    old = {}
    if os.path.exists(JS):
        t = open(JS, encoding='utf-8').read()
        old = json.loads(t[t.index('{'):t.rindex('}') + 1])
    # FIFA 23: specials at level 0, base cards (0 common, 1 rare) at levels 1-3 (bronze, silver, gold)
    for year, pre in (('2022', 'f22'), ('2023', 'f23'), ('2024', 'fc24')):
        for rid in range(0, 200):
            for lvl in ((1, 2, 3) if rid in (0, 1) else (0,)):
                key = f'{pre}-{rid}' + (f'-{lvl}' if rid in (0, 1) else '')
                if os.path.exists(os.path.join(OUT, key + '.webp')) and key in old:
                    designs[key] = old[key]; continue
                data = get(f'{CDN}{year}/rarities/{rid}_e_{lvl}.png')
                if data:
                    save(key, data, designs)
    # FC 26 / 27 from the cached fut.gg pages
    paths = set()
    for fn in os.listdir(a.cache) if os.path.isdir(a.cache) else []:
        s = open(os.path.join(a.cache, fn), encoding='utf-8', errors='replace').read()
        paths.update(re.findall(r'(20(?:25|26|27)/rarities-level-(\d)-large/(\d+)\.[0-9a-f]+\.png)', s))
    for path, lvl, rid in sorted(paths):
        key = f'fc{path[2:4]}-{rid}-{lvl}'
        if key in designs:
            continue
        if os.path.exists(os.path.join(OUT, key + '.webp')) and key in old:
            designs[key] = old[key]; continue
        data = get('https://game-assets.fut.gg/cdn-cgi/image/quality=90,format=png,width=420/' + path)
        if data:
            save(key, data, designs)
    lines = ['// GENERATED by tools/fetch_card_designs.py: EA SPORTS FIFA 23 / FC 26 / FC 27 card backgrounds (fan use, non-',
             '// commercial) in assets/cards/<key>.webp. ink = text colour for that background, dark = light-on-dark text.',
             '// Keys: f23-<eaRarityId>[-<level>], fc26-<eaRarityId>-<level>, fc27-<eaRarityId>-<level> (level 1-3 = bronze/silver/gold).',
             'export const CARD_DESIGNS = ' + json.dumps(dict(sorted(designs.items())), indent=0).replace('\n', '') + ';', '']
    open(JS, 'w', encoding='utf-8').write('\n'.join(lines))
    print(f'{len(designs)} designs', file=sys.stderr)


if __name__ == '__main__':
    main()
